// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaExpediente.Domain;

namespace NovaExpediente.Persistence.Migrations
{
    [DbContext(typeof(NovaExpedienteDbContext))]
    [Migration("20180607065932_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NovaExpediente.Domain.GradoAcademico", b =>
                {
                    b.Property<int>("IdGradoAcademico")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdGradoAcademico")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Descripcion")
                        .HasColumnType("ntext");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdGradoAcademico");

                    b.ToTable("GradoAcademico");
                });

           
#pragma warning restore 612, 618
        }
    }
}
